name: marcusdyer
favicon: null
layout_spectrum: 0.756178796524182
typography_spectrum: 0.8074796963483095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1f18'
    - '#746256'
    - '#ace294'
    - '#8bb06d'
  brandStrength: 0.7947679371573031
  lightness: 0.6372817032970488
  saturation: 0.16189542319625616
  rhythmicContrast: 0.8806303690653294
purpose: []
